apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphr-dpl
  namespace: graphr
  labels:
    app: graphr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphr
  template:
    metadata:
      labels:
        app: graphr
    spec:
      # Specify the service account that has the appropriate SCC
      serviceAccountName: shiny-sa
      containers:
      - name: graphr
        image: quay.io/michard/graphr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3838
          protocol: TCP
        securityContext:
          runAsUser: 997  # UID for the 'shiny' user
          fsGroup: 997     # GID for the 'shiny' group
      # Ensure that the pod uses the correct security context
      securityContext:
        fsGroup: 997
---
apiVersion: v1
kind: Service
metadata:
  name: graphr-srv
  namespace: graphr
spec:
  selector:
    app: graphr
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3838
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: graphr-route
  namespace: graphr
  labels:
    app: graphr
spec:
  to:
    kind: Service
    name: graphr-srv
  port:
    targetPort: http
  tls:
    termination: edge